export const GET_PRICEPLANS = 'GET_PRICEPLANS';
export const ADD_PRICEPLAN = 'ADD_PRICEPLAN';
export const DELETE_PRICEPLAN = 'DELETE_PRICEPLAN';
export const UPDATE_PRICEPLAN = 'UPDATE_PRICEPLAN';
export const SAVE_PRICEPLANS = 'SAVE_PRICEPLANS';
export const FIND_PRICEPLAN = 'FIND_PRICEPLAN';
